### ISSUE TITLE
Dexterity items don't get have Symptoms available

### ISSUE THREAD

**Issue by djowett** [gotcha/collective.jekyll#16]
It seems we only have the 3 Symptoms:

* title length
* short name format 
* title format

which correspond to those subscribed to the `IMinimalDublinCore` in [configure.zcml](https://github.com/gotcha/collective.jekyll/blob/master/src/collective/jekyll/configure.zcml#L51) 

![collective jekyll_missing_symptoms](https://cloud.githubusercontent.com/assets/1470021/15406258/ad50d89e-1dfd-11e6-9354-84fdc9a4a8f2.png)

I'm using plone.app.contenttypes in Plone 4.3

**Comment by gotcha** [comment]
PR welcome.

The process here is really inspired by http://rfc.unprotocols.org/spec:1/
